### ISSUE TITLE
Add Organizations

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/zenodotus#117]
- [x] Each user must be associated with an organization
- [x] Ability to set user as admin
- [ ] Organization admins are the only ones who can add users
- [ ] Super admins are the only ones who can create an organization and add the initial admin
 - [ ] "Request access" link which creates a "request organization" and then that gets upgraded by a super admin (this will include a "contact email address")

**Comment by reefdog** [comment]
As with #74, putting this on ice after @cguess consultation since we don't have a full enough understanding of the organizational use case, and will be hiding organization-related interface.

**Comment by reefdog** [comment]
We've decided not to pursue orgs at all; closing this and will be removing organization code in #302.
