### ISSUE TITLE
Set up third party storage and upload

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/zenodotus#205]
This is an archive, however, we use ephemeral containers right now for everything (scraping and storage). This is a problem, since every time the server resets all the data will disappear (on Zenodotus) and fill up all the bandwidth (on Hypatia). Instead, it'd make sense to use S3 (maybe something else?) as a storage backend. This would mean Hypatia uploading results to S3 and then sending an id in the response.

Pros:
- This has the benefit of dramatically lowering our REST call size (which is unreliable anyways)
- don't lose our data (probably number 1 reason)

Cons:
- More steps
- having to deal with AWS credentialing

**Comment by cguess** [comment]
This graph describes the work flow that I'm seeing (link to edit below the image).
![Untitled-3](https://user-images.githubusercontent.com/322626/166311001-9edf504d-8fb6-4588-ba00-939f8cccb428.png)
https://sequencediagram.org/index.html#initialData=A4QwTgLglgxloDsIAIBaBTBB7AJliArgM4BQoks8ISyAEgJ6jQgk4gQgBGIR6yAggHUAysmEBmOo3ZQQyAEIEYAa3QRW7Ljz5DREtJlz5iCpavUloEADZ9hMMCGDocyALIvZYiFkcBzPgAxaywAdxISDGw8QiJkAFoAPgYmWQAuZAAldABHAnQiFHtHZxIUmRB4pKijWIyAJgAGRuQAeQBpMulmBOTu9LEHJzsoCHQu1Lkk3TFJcp7FFTUMgFVgEJBXIiHnVwAzKFsSbDHkLAA3dDABEVmpSdMliAyAFQALKDjOMzVkN55kHIsJwAFboGAoaAAW3QWAIKGAWGssHoAB1sHtAcg9uhQsg2PQ4kQsMgIP8UKE+HgEAByCDo-6XUkk0K+MD0QGcOEoHDoWzQBB+M6g8EQUgzfTzLyLcy9KUgDIy36tEUQ5AASQAIhMKtVDDFiBlisNsVAEJ83i5kDAQNZrNwVOjQqM3shvk9hWCYMgoPtfKajjUDUQADzTW6S-pyJXPZCasIIDZbHZWmE4WSRfXGIh66LZjIABTAWBgBTiaYzQez4b0kirsUe5iNPjAfArcj2-oAXlmGwAKMmfZDEApiN5gM3oGlfAiHAV3HHsAitogASiAA

**Comment by reefdog** [comment]
This can be closed now, yeah @cguess?
