### ISSUE TITLE
Video search doesn't yield results for some searches

### ISSUE THREAD

**Issue by oneroyalace** [TechAndCheck/zenodotus#213]
Two examples:

https://www.youtube.com/watch?v=CrH0I6ztmEI
https://www.youtube.com/watch?v=Df7UtQTFUMQ

Image hashes are created for both posts, but video search returns no matches. 

To reproduce: 
1. In the rails console, `Sources::YoutubePost.create_from_url! "https://www.youtube.com/watch?v=RWsputad5ZU"`
2. In the terminal, `yt-dlp -f mp4 -o vid.mp4`
3. Upload vid.mp4 to Zenodotus' media search

Expected result: Zenodotus' media search returns matched media:
Observed result: Zenodotus' media search doesn't return any hits

**Comment by reefdog** [comment]
Perhaps this is a stress test, but it's a real-life one: I screenshotted a frame from the Lumberjack video (from the database seed), [as it appeared on Twitter](https://twitter.com/archives33/status/1409322086875766787). Of course this is a silly way to get a high-quality frame from the video, but it's likely representative of real-world use, so I tried.

Here's the frame; I was letting it play at whatever size the Twitter web interface displayed it, made sure the controls were hidden, and screenshotted as as close to possible to the frame edges. Basically, best case scenario for normal humans.
<img width="565" alt="lumberjack-screenshot" src="https://user-images.githubusercontent.com/4731/167013909-c8bf2319-976f-46cd-a199-c652c00fc4e9.png">
