### ISSUE TITLE
Single Facebook author imported as multiple users

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#239]
I just loaded up https://zenodotus-staging.herokuapp.com and noticed that the two most recently-archived pieces of media (at this moment) are from the same Facebook account, yet if you drill in to their user page, they're treated as distinct Facebook users within the vault. It looks like we may sometimes be creating a new user record for every archive item.

Example of three users that should be one:

- https://zenodotus-staging.herokuapp.com/facebook_users/8274ed34-0445-4494-aa86-959d7f978e7e
- https://zenodotus-staging.herokuapp.com/facebook_users/54c4ddaa-e544-4592-86fc-404b83614cc8
- https://zenodotus-staging.herokuapp.com/facebook_users/3541c332-afbc-424b-ae90-f1893040abda

**Comment by cguess** [comment]
This is weird, we even have a test to handle this. 

```
  test "can update facebook user" do
    archive_entity = Sources::FacebookUser.create_from_forki_hash([@@forki_user]).first

    # Set a property to something random
    archive_entity.facebook_user.update!({ followers_count: 2 })
    assert_equal archive_entity.facebook_user.followers_count, 2
    # Now try and save it again, and make sure the followers count is correct
    archive_entity2 = Sources::FacebookUser.create_from_forki_hash([@@forki_user]).first.facebook_user
    assert_equal archive_entity.service_id, archive_entity2.service_id
    assert_equal @@forki_user["number_of_followers"], archive_entity2.followers_count
  end
```

**Comment by cguess** [comment]
Whoops, the problem is we were looking at `id` in the Zeno database instead of `facebook_id`
