### ISSUE TITLE
Facebook previews on user page don't play video

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/zenodotus#252]
If you go to a user's page with a Facebook video post on it we only show the preview with no way to play it. Fix this.

**Comment by reefdog** [comment]
@cguess I can't replicate this. When I go to a user's page, of any kind platform (including Facebook), I'm able to play the video.

We are using the native `<video>` tag and its native controls, which are hidden after a moment of inactivity. But you can click the video area to start playing, or hover (on desktop) to reveal controls.

Can you verify that this issue exists, and maybe we can screenshare about it if so?

**Comment by reefdog** [comment]
Talking w/@cguess, this was meant to be about preview images not videos, thus a dup of #258.
