### ISSUE TITLE
Fix preview images of videos not loading

### ISSUE THREAD

**Issue by oneroyalace** [TechAndCheck/zenodotus#258]
It *seems* as if the preview images of videos aren't being used when loading the MediaVault's home page and search results. This is problem because that means that the whole video is downloaded before showing the preview, which on slightly slower connections leaves a large white box and nothing else for awhile. On mobile this kills data.

This could be released to the previous issue of some images still being sent over Base64, or it could be an inline issue. Unsure, but we need to look into it ASAP.

Note: You won't notice this when testing locally since the video loads so quickly.

**Comment by reefdog** [comment]
@oneroyalace So, we have two possible overlapping issues here.

#### 1. Are we using the correct image for the `<video poster>` attribute?

When generating the `<video>` element, I set `poster="<%= media.video_derivatives[:preview].url %>"` [here](https://github.com/TechAndCheck/zenodotus/blob/98722cd2f672237409e2307ec32f25ac6e36bec4/app/views/archive/_archive_item_media_inline_full.html.erb#L10).

**Is this correct?** Does that actually point to the preview image? Or is that just naively grabbing the first frame of the video or something? The composition of these media objects is a little complicated so I'm not sure if there's a more appropriate attribute.

**Resolution to ①:** If @cguess or @oneroyalace can verify the correct attribute for me to grab the poster image, I'll update it (if necessary).

#### 2. Is the browser trying to preload all the videos on the page?

We aren't using the `preload` attribute, which means that on most current browsers with semi-fast connections, the browser is defaulting to `preload="auto"`, which means it's preloading all the videos on the page. 😱

IMO, we should change this to `preload="none"`. The only page that should have `preload="auto"` is a single-video page, like a canonical page for a single piece of media, which we don't even have right now. Any performance gains of preloading in the background are offset by the likelihood of dragging down the user experience (and wasting bandwidth) needlessly.

**Resolution to ②:** I'm going to set the videos to `preload="none"`.

**Comment by reefdog** [comment]
This has been closed by #294, but to document history: in a convo w/@cguess he confirmed `media.video_derivatives[:preview].url` is the right attribute for the poster image (but plans to look into it just to be sure), and that `preload="none"` should address the issue of browsers sometimes skipping the poster to auto-download the video (both for its own sake and for video metadata it would otherwise get from the poster, like dimensions).
