### ISSUE TITLE
Provide final content edits

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#266]
After all else, do a final pass on the site, updating any placeholder content, editing what's there, and giving it a final sign-off.

**Comment by ericaryan** [comment]
We're still figuring out what's going on with a few fields, but the descriptions for the schema table are here: https://docs.google.com/spreadsheets/d/1ZiV8-ks4AL2wqeKKkcuoI84GdMRZUE8xSQ87tCh2-8k/edit?usp=sharing

**Comment by ericaryan** [comment]
Tiny little edits, but on the Guide to the Data page:

In the MediaReview box: "interested in tagging their articles with ClaimReview [ADD: and MediaReview]"
In the Tips box: Under "A ratings exception": Link to the full MediaReview Ratings on either the phrase "standard ratings" or "Those ratings"
https://www.claimreviewproject.com/mediareview/definitions-and-examples
