### ISSUE TITLE
Architect registration/approval process

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#268]
We intend to gate the Insights data behind user authentication, and to require human approval for user registration.

### Process:

1. Applicant fills out a form to request an account; form includes email address
2. Applicant has to confirm their email address
3. After confirmation, admins are notified of a new pending request
4. Admins must reject or approve the request; applicant is notified of decision
5. If approved, applicant is converted to user (with blank password) and must complete registration by choosing a password

### Technical notes:

- For security, user accounts won't be created until admin has approved the application. `Applicant` will be its own table.
- Password-creation flow will essentially be the "password reset" flow, but with a custom email template—and custom site template, if possible. (At the very least, UX and copy should reflect each respective flow.)
- Applicant email confirmation _may_ use the same piping as user email confirmation (e.g. for email changes), if that's possible/easy. But it doesn't need to; we can roll our own for applicants if necessary since security considerations are lighter there.
- We will need to enforce uniqueness constraints between applicants and users — e.g., no creating an application for an existing user's email address, or changing an existing user's email address to the same email as an applicant — but **without leaking existence**.
   - If a new application is opened for same email as existing **applicant**: pretend like we don't know that (to the browser-user), accept the duplicate request, but notify admins of the redundancy so they can decide what to do. (Definitely don't let more recent requests stomp on / delete existing requests; that could be misused.)
   - If a new application is opened for same email as existing **user**: pretend like we don't know that (to the browser-user), don't accept the duplicate request, but do contact the existing user to say "hey, someone just tried to open an account as you; if that was you, you have an account and can log in. If that wasn't you, yikes! Be careful!"
   - If a user tries to change their email address to the same email as a pending applicant… well, that would be weird, but we should follow the same process we'd follow if they tried to change to the email of an existing user. (Error out vaguely in a way that doesn't leak the existence of the other account.)

### User flow notes:

- Applicants won't be able to "check their status" except through manually emailing to ask.
- Rejected applicants won't be able to automatically appeal / re-apply. They'd just have to do it manually. (Currently we have no intent to block them from doing so.)

### Open questions:

1. What fields does the application need to contain? (And which are required v. optional?)
2. When an admin rejects an applicant, do we want an **internal/private** Reason/Explanation field?
3. …do we want an **external/public** (communicated to the applicant) Reason/Explanation field?

**Comment by reefdog** [comment]
### Request access:

1. User fills out request form
2. Request object created with "pre-confirmation" status; no user account created (because security boundary)
3. User must confirm email address
4. After confirmation, request changes to "pending" and admin is notified
5. If admin rejects, request is closed and user notified
6. If admin accepts, user account is created and password reset process triggered with custom email template

#### Additional states/considerations
- Email confirmation process can be something we roll ourselves; security concerns are lower than when existing users are modifying their email addresses since this is about requests, not "real users".
- Be careful not to leak existence of existing requests.
   - If request is opened for same email as existing **request**, pretend like we don't know that (to the browser-user), accept the duplicate request, but make sure admins can see that there are two requests for the same email account so they can decide what to do. (Definitely don't let more recent requests stomp on / delete existing requests; that could be misused.)
   - If request is opened for existing **user**, pretend like we don't know that (to the browser-user), don't accept the duplicate request, but do contact the existing user to say "hey, someone just tried to open an account as you; if that was you, you have an account and can log in. If that wasn't you, neat! Be careful!"

**Comment by reefdog** [comment]
### Users

- Look at [CanCanCan](https://github.com/CanCanCommunity/cancancan) and [Rolify](https://github.com/RolifyCommunity/rolify)
- Two primary roles: Admin (internal / Duke person) and User (external)
- Within users, the only permission so far is "has MediaVault access", but could have others in the future
- Email changes must be confirmed
- MFA stretch goal (Authenticator app at least, security key preferred)

**Comment by joelwluther** [comment]
> 1. What fields does the application need to contain? (And which are required v. optional?)
I like these:

Name:                           [              ]
Email address:              [              ]
Organization affiliation (if any):       [              ]
What is your primary role?             (Select one…)
How do you plan to use the data?  [              ]
[ ] Accept T&Cs?

I'd say of them, organizational affiliation can be optional (or at least free text that accepts something like "none" or "n/a" but I think the rest should be required.

> 2. When an admin rejects an applicant, do we want an internal/private Reason/Explanation field?
This is one of those things that would be great to have, but I don't think is strictly necessary. Great for being able to refer back to if they pop back up again, or if a similar application pops up so we can go back to compare notes. But, we could also manage that in a Google Doc/Sheet -- if it's a huge lift to build into the platform, not necessary.

> 3. …do we want an external/public (communicated to the applicant) Reason/Explanation field?
Almost certainly want to communicate a reason/explanation via email when we get to that step in the approval process -- maybe when the admin goes to approve/reject there's a drop-down that lets us select a "reason for rejection" that gets sent in that email to the would-be user. But if they're not actually becoming users until after they're approved, I don't think they need to be able to "log in" and be presented with a "You were rejected because......" message, if that's what the question was.

**Comment by reefdog** [comment]
These are all great, thanks Joel!

Re: internal Reason/Explanation field, it's super easy to add and no trouble at all. I'll plan to add it.

Re: external Reason/Explanation field:

1. You're correct that they won't be able to "log in" to view the reason since they won't have an account. This reason would just be included in the rejection email that was sent to them. Also, it would be optional; the admin could just leave it blank if they wanted. (The internal rejection field should be required, IMO, although the admin can just pick "Other" and provide no explanation.)
2. Should the external rejection reason be a drop-down menu of pre-selected options, plus an "Other" that allows fuller description? I guess the question here is how much explanation you want to provide the person in advance. If just a couple of words "Not in industry" then we can make do with drop-downs. If you intend to write a personalized note to the person, then a multi-line text field would be better.

**Comment by reefdog** [comment]
It sounds to me like we have the _architecture_ of registration/approval good to go, and the remaining issues (about how to express the "reason" UI) are details we can sort out during implementation.
