### ISSUE TITLE
Architect authorized data download

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#274]
Insights data will be delivered as compressed blobs that only authorized users can download.

### Format

JSON for sure, TBD whether we can deliver it in other formats (incl. flat tables like CSV).

### Generation

We could generate the data two ways:

1. **On demand:** When the user requests the data, the server generates it and delivers a download response.
   - **Pros:** Data is freshest. Authentication is simple.
   - **Cons:** More taxing on the server. Server responsible for bandwidth.
2. **Periodic snapshots:** Every hour (or whatever), the server generates a new file (if necessary) and uploads it to S3. Access is gated by time-bombed user-specific tokens generated at download request time.
   - **Pros:** Less taxing on the server. Lower bandwidth requirements.
   - **Cons:** More complicated authentication. Data as "stale" as our update cadence.

An additional consideration: our Visualizations page will be driven by a summary snapshot of the data. (E.g., rather than drive the graphs from a live querying of the database, we'll deliver a small static JSON file with the current values for the graph.) This snapshot will need to be updated periodically. If we went with method ②, we would update this summary file at the same time as generating the download blob. If we went with method ①, we'd still need to have a separate process for updating that summary file.

### Authentication

As alluded to in the Generation section, authentication depends on whether we're generating the download on-demand or delivering it via an S3 store.

1. On-demand is simple and would act like any other authenticated request since the entire request was fulfilled within Rails.
2. Periodic snapshots would be a little more complicated and require interaction with S3. When the user requests a download, we have S3 generate a time-limited token, and then we pass that token back to the user. Then the user requests the file from S3 using that token. This is obviously a bit more complicated than the on-demand model; the server has to handle errors in token generation (and pass those errors to the client), and then the client has to handle errors in token usage.

### Open questions

1. **What's the best way to provide CSV downloads**, given CSV's unfriendliness to nested object relationships? @oneroyalace proposed splitting Claim Review and Media Review into separate flat files with a foreign key tying them together where applicable. I like this idea.
2. **What generation method should we use, on-demand or snapshot?** We could start with on-demand (it's "free") and then add snapshotting as needed.

**Comment by reefdog** [comment]
@cguess I wrote up our discussion above, but fleshed out the alternative naive approach (on-demand downloads) as a strawman. Yet, now I'm wondering if we don't go with the strawman first and add the S3+token snapshot approach as a second phase? What do you think?

**Comment by joelwluther** [comment]
> What's the best way to provide CSV downloads, given CSV's unfriendliness to nested object relationships? @oneroyalace proposed splitting Claim Review and Media Review into separate flat files with a foreign key tying them together where applicable. I like this idea.

I like that idea too; if it's helpful, below is an ex of how Google's [FCMT JSON feed](https://storage.googleapis.com/datacommons-feeds/factcheck/latest/data.json) **(warning: this is a 74.5MB file so it might kill your browser)** lists them.

While tying them together with a unique ID would be great, they should already be tied via the article URL (it should be the same in every case). But researchers love unique IDs for other purposes, so...

Ex:

```
    {
      "@type" : "DataFeedItem",
      "dateCreated" : "2022-08-01T13:45:34.804509+00:00",
      "item" : 
      [
        {
          "@context" : "http://schema.org",
          "@type" : "ClaimReview",
          "author" : 
          {
            "@type" : "Organization",
            "name" : "dpa",
            "url" : "https://dpa-factchecking.com/"
          },
          "claimReviewed" : "Collage toont aan dat dezelfde auto werd gebruikt voor drie verschillende auto-ongelukken",
          "datePublished" : "2022-08-01",
          "itemReviewed" : 
          {
            "@type" : "Claim",
            "appearance" : 
            [
              {
                "@type" : "CreativeWork",
                "url" : "https://www.facebook.com/max.dejonge.988/posts/pfbid02TCDAxqk36WcK7YUM4QQXUCRymL2yMgMfxb8PL9gPUpGB8BK5tqGovcNDwtqvrrp9l"
              }
            ],
            "author" : 
            {
              "@type" : "Person",
              "name" : "Max De Jonge"
            },
            "datePublished" : "2022-07-29"
          },
          "reviewRating" : 
          {
            "@type" : "Rating",
            "alternateName" : "De claim dat dezelfde auto betrokken was bij drie verschillende ongelukken is onzin. In de bovenste foto van de collage is de witte Renault gefotoshopt. De onderste twee foto’s zijn van hetzelfde ongeluk. Deze crash gebeurde op 27 juli 2022 bij Meppel, na een aanrijding met de berg hooi en balken."
          },
          "sdPublisher" : 
          {
            "@type" : "Organization",
            "name" : "Google Fact Check Tools",
            "url" : "https://g.co/factchecktools"
          },
          "url" : "https://dpa-factchecking.com/netherlands/220801-99-233777"
        },
        {
          "@context" : "http://schema.org",
          "@type" : "MediaReview",
          "datePublished" : "2022-08-01",
          "mediaAuthenticityCategory" : 
          [
            "TransformedContent"
          ],
          "mediaType" : 
          {
            "@type" : "Image"
          }
        }
      ],
      "url" : "https://dpa-factchecking.com/netherlands/220801-99-233777"
    }
```

**Comment by cguess** [comment]
> @cguess I wrote up our discussion above, but fleshed out the alternative naive approach (on-demand downloads) as a strawman. Yet, now I'm wondering if we don't go with the strawman first and add the S3+token snapshot approach as a second phase? What do you think?

@reefdog I think I see where you're coming from. The coding is simpler to not have to deal with caching yet. I'd say sure, we can see how long the processing takes, it may be very quick.

**Comment by cguess** [comment]
In regards to some questions from @reefdog:
> What’s the best way to provide CSVs? If we split Claim Review and Media Review data into two files (with a foreign key tying them together where applicable), does that handle it?

Wait, why are we exporting in CSV? I thought we had agreed on JSON output?

> Should we phase the download by starting with on-demand file generation and only later adding the S3 snapshot?
Yes, I think so.

**Comment by reefdog** [comment]
> Wait, why are we exporting in CSV? I thought we had agreed on JSON output?

We're definitely providing JSON. The point came up that, if possible, we should **also** provide CSVs since academics love working with them.

**Comment by cguess** [comment]
But this isn't quantitative data, so it wouldn't make much sense? I imagine most researchers using this data are going to be ingesting it into some sort of software that's not excel.  I'm afraid of building something that people won't use.

**Comment by reefdog** [comment]
> While tying them together with a unique ID would be great, they should already be tied via the article URL (it should be the same in every case). But researchers love unique IDs for other purposes, so...

I'm ambivalent about _what_ the foreign key is. Totally agree that if there's an existing attribute that can be relied upon for this purpose — not just as an ersatz one but because definitionally it really does tie objects together — then that's better than generating one. I'd definitely prefer not to have to generate one just for the purposes of this download.

**Comment by reefdog** [comment]
@cguess We could always just start with JSON and wait for the requests to come in, I suppose.

**Comment by cguess** [comment]
They're not flat though, they have publisher, and creator data that is nested

**Comment by reefdog** [comment]
Ah okay that's useful information! There was a convo in #devshop on Friday about this that seemed to make flattening it seem more doable; @joelwluther said he'd done it for people, though maybe that was through a very manual/custom process that isn't generalizable. If the consensus is it's _not_ generalizable, then yeah, let's not do it.

**Comment by cguess** [comment]
I'd say let's call it a premature optimization. Every CSV with id's field I've worked with it's mostly just to get it back into a nested data set anyways.

**Comment by reefdog** [comment]
Okay, I'm gonna call this architecture complete then, with these choices:

- Format: **JSON only for now**, CSV explored once the need becomes more clear.
- Generator: **On-demand generation/delivery**, with S3 snapshots explored once needed.
   - Visualizations: I think the answer here (since on-demand means no natural cadence) is to just bake the numbers into the rendered page and let the Rails cache expire the page periodically. Either way that's a slightly tangential issue so shouldn't hold up this one.
