### ISSUE TITLE
Design visualizations and analysis for Visualizations/Highlights page

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#276]
Our Visualization/Highlights/Examples/whatever page is meant to show off a few interesting uses of the Insights data. Thus, we should think through 3–4 cool insights to draw from the data and how to illustrate it. This issue is for the thinky part of that. There are separate issues for the actual building of it.

The deliverable of this issue should be either:

- Clear descriptions of each graph on the page (data composition, chart type, axis labeling, etc.) from which a developer could build the graph, or…
- URLs of existing graphs to embed (if we go the "just use Thomas's" route or similar).

**Comment by joelwluther** [comment]
Some ideas based on stuff I've done one-offs of in the past:

1. A cumulative count of ClaimReviews by year:
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/83415978/182933478-27ee6659-79c1-42c4-b1fc-7227bab0208f.png">
2. A map showing either of outlets by country represented in the data set.
![image](https://user-images.githubusercontent.com/83415978/182933671-c691cae9-6f50-4e70-9271-933410e2f710.png)
3. Table showing entries per organization:
![image](https://user-images.githubusercontent.com/83415978/182933905-c53d331a-285a-46be-bf29-365a5d3dff90.png)

**Comment by reefdog** [comment]
Oh, interesting! A very low-cost way to get these viz into the site would be to just embed some of Thomas' graphs (if permitted). We'd have to note that the numbers were based on data as of [whenever], and/or make sure to update the data feeding those graphs, but it'd be a super-fast way of adding them.

**Comment by ericaryan** [comment]
I like the outlets per country (or entries per country), especially if there was a way to do a comparison of 2016 versus now. I also like showing the number of ClaimReview entries growing by year.

My concern with using Thomas' data is that it only goes through 2020 and to update it we might have to do a lot of data cleaning (depending on what we choose to show). But I'm open to discussion.

I do think it would be good to consider at least one social media-focused visualization. I like Thomas' graph showing the the source of fact-checked claims by platform over time.

**Comment by joelwluther** [comment]
@reefdog is there a middle ground here where we use an external data vis solution, like Thomas did with Tableau, and have those dashboards linked to the "live" data as it updates? I've done something similar years ago (in terms of making Tableau views auto-update) with [Zaiper](https://zapier.com/), though I'm sure there's a more elegant solution.

I've got decent Tableau experience and am happy to work on designing the views if we can successfully link them to live data.

**Comment by reefdog** [comment]
@joelwluther Very possibly! I've not implemented this before, but if Tableau can be driven by a remote data source, then we can be sure to _be_ that remote data source.

We'd still need to make sure that source was protected in some way, e.g. through an API key that Tableau is configured to use or by stripping the source down to just the attributes needed to build the Tableau graphs. (Otherwise, we'd be publicly providing the dataset, which defeats the whole purpose of login/authorization.) But not having to build the dataviz itself cuts our dev load for the page way down.

**Comment by reefdog** [comment]
We've come up with a plan for these visualizations, and will implement them in further tasks.
