### ISSUE TITLE
Write terms & conditions for the site

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#289]
We will need T&Cs for the FCI site. I've no idea how to write them, I'm just the messenger!

**Comment by ericaryan** [comment]
https://docs.google.com/document/d/1R8OG0hREaLDHyID4-V1m2OmhoBOBL1yTOIA7ZBpUgfQ/edit?usp=sharing

**Comment by cguess** [comment]
Done

**Comment by ericaryan** [comment]
Make the "contact us" at the very end of the TOS a text link to the Contact page
