### ISSUE TITLE
Point mail.factcheckinsights.com MX records to Mailgun

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#303]
In #281, we settled on using our existing Mailgun account for sending transactional email from the FCI site. We need to point the FCI domain's MX records to Mailgun so we can send through it.

Since we don't use Mailgun for receiving email, and want to leave the door open for `@factcheckinsights.com` email inboxes, we're going to use `mail.factcheckinsights.com` as the domain instead.

So: let's setup `mail.factcheckinsights.com` and point its MX records to Mailgun: https://app.mailgun.com/app/sending/domains

**Comment by cguess** [comment]
All done.
