### ISSUE TITLE
Decide Insights/Vault split better

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#306]
Having walked through the proposed design (#285), the team realized that the existing information architecture that had Media Vault as (1) integrated tightly under Fact-Check Insights, and (2) completely hidden until a user was provided access, wasn't right.

- [x] Propose different models/designs for balancing the two properties (@cguess)
- [x] Meet to discuss models and sign-off on one (@joelwluther)
- [ ] Update architecture documents accordingly (@reefdog, #307)

**Comment by reefdog** [comment]
Chris wrote out a [menu of options](https://docs.google.com/document/d/1FOTiiTqk7bux0N4fpzsyOWlC5CmyuqF6_2Ouyt3ouoc/edit) and the team met on 8/16 to discuss, then presented it for sign-off by Bill on 8/17. Here's the proposed and signed-off plan in summary, which is essentially [Option C](https://docs.google.com/document/d/1FOTiiTqk7bux0N4fpzsyOWlC5CmyuqF6_2Ouyt3ouoc/edit#heading=h.fdaror71fou9):

- Insights and Vault will be presented on their own respective domains, but both hosted by the same Rails app.
   - The sites will share a layout and design language, the one presented by Joanna in #285. Each of them will have their own brand-appropriate color theme and content/navigation.
   - Some content may be re-usable between the two sites, such as "About the Team" or T&Cs and such. With this all being in the same Rails app, this is easy.
   - The Vault site will likely be hidden from search engines with its `robots.txt`.
- Authentication will continue to be shared between the two sites; users will only have a single set of credentials.
   - We're keeping the same model of "anyone granted a user account will have access to Insights; only certain users will be granted access to Vault".
   - Authentication — including applying for an account — will occur at a third domain, probably auth.factcheckinsights.com, which is _also_ hosted by this same Rails app.
   - This will be very stripped-down — think Auth0-hosted sign-in pages, but with brand-consistent layout and design. References to the platform ("Fact-Check Insights" or "Media Vault") will be customized based on which respective origin site the user came from.
   - From either Insights or Vault, clicking any Log In or Sign Up links will go to this central domain ("the land of wind and ghosts"). After successful authentication they'll be bounced back to their respective origin site.
   - Because this domain matches Insights, Insights will "just work", but Vault will need to be an OAuth consumer (or something similar).

@cguess Does this match your understanding?

**Comment by cguess** [comment]
This matches what I'm thinking. I would like to add one caveat that if the domain thing is becoming an impediment for us, such as in authentication, we can do a redirect. It could be that the separate domains point to landing pages, and as soon as you go to login you instead end up on a subdomain, getting around the one-domain-per-cookie security limitation.

Another possibility would be that, when we log someone in, we redirect them around to all the domains we want to authenticate them on. Each page does two things: sets a cookie, and the redirects to the next page. This would be a bit of a hassle but could allow us to keep the separate domains while also allowing logging in to both. Then on log out we just delete the auth key in the cookie an no domain will authenticate anymore.

Thoughts?

**Comment by cguess** [comment]
>> It could be that the separate domains point to landing pages, and as soon as you go to login you instead end up on a subdomain, getting around the one-domain-per-cookie security limitation.
> I think this is what I described above, unless you mean that the entire authentication and post-authenticated app experience for both apps would be hosted on the same domain. E.g., we have factcheckinsights.com and mediavault.com (or whatever) marketing sites, but then logging in and using them happens at app.factcheckinsights.com (and then app.factcheckinsights.com/vault or whatever). Is that what you mean?

I think we might be talking about the same thing. The way I see it is this:
`mediavault.com click "login" --> login page @ auth.factcheckinsights.com --> authed and redirect to vault.factcheckinsights.com`

**Comment by reefdog** [comment]
Oh sweet! Okay so then how would you feel about the `mediavault.com` → `vault.factcheckinsights.com` redirect happen at the DNS level rather than just post-login? Because in _that_ case, it's _super_ easy and we don't even need the `auth.factcheckinsights.com` domain. We can literally just let `factcheckinsights.com` and `vault.factcheckinsights.com` appear to be two different sites, each with their own login forms, but really those are the same forms (in different layouts) pointing to the same auth controllers, and we ensure the taken is valid for both (since rooted at the same domain).

The only real difference between that and your model is in your model, the redirect to `vault.factcheckinsights.com` doesn't come until after login. Personally if we're going to end up serving Vault at a subdomain anyway, then I'd _love_ to flatten the stack entirely and just use `mediavault.com` as the domain people memorize / we market.

**Comment by cguess** [comment]
Idk, I'd rather do the redirect when you go to the login page, but the landing page stays the same. Does that make sense? Should still be doable no?

**Comment by reefdog** [comment]
Doable, sure, I'm just figuring that if we can get away with _not_ having the `auth.factcheckinsights.com` domain, that saves us a significant amount of UI/UX work.

If you're suggesting we serve the landing page (+about, contact, etc.) at `mediavault.com` but then host Vault's login page on `vault.factcheckinsights.com/login` (and Insight's login page at `www.factcheckinsights.com/login` or whatever), then I guess that's fine?

I'm just hoping that, if we're cool with `vault.factcheckinsights.com` being in the running, that we can avoid the `auth.factcheckinsights.com` complication entirely.

**Comment by cguess** [comment]
yes, that's fine. As you said, we can just wrap the login form with the styling for each side. Good job!
