### ISSUE TITLE
Determine footer content

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#310]
We currently lack any direction for the footer content: what partners/logos we want to include, how full of a sitemap, any legal boilerplate, etc.

- [x] Add footer content area to Content Architecture document (@reefdog)
- [x] Fill out the content (@joelwluther)

**Comment by reefdog** [comment]
Here's the footer content area and a starting point (based on Joanna's excellent placeholder in the XD): https://docs.google.com/document/d/1IXfbbfHew7bq4emEeXNC99-3vR0uA1HWP3dP5g43BLM/edit#heading=h.a9o8thsp70uv

**Comment by joelwluther** [comment]
Added content to the [doc](https://docs.google.com/document/d/1IXfbbfHew7bq4emEeXNC99-3vR0uA1HWP3dP5g43BLM/edit#heading=h.a9o8thsp70uv)!
