### ISSUE TITLE
Add technical content/details to the Guide page

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#311]
Once we're generating the data (#275), we need to add some technical content to the Guide page:

- [x] **Tips**: A few things we've learned about working with this data
- [x] **Format:** What you can expect when you download the data (file type, schema, etc.)
   - [x] Create sample markup/styling @reefdog 
   - [x] Provide content (in progress) @joelwluther @ericaryan 
   - [x] Fill in table with content @cguess
   - [x] Do final fixes/tweaks @reefdog 
      - [ ] Remove "Data Type" column
      - [ ] Rename "Value" column to "Example"
      - [ ] Remove outer brackets (first/last row) and reduce indentation of all cells by 1 level
      - [ ] Change tbody border color to `#e5e5e5` (and make new variable for thead border)
      - [ ] Zebra-stripe between `#f7f7f7` (odd) and white (even)
      - [ ] Add a `Math.min` function to the `.na` line-height so it maxes-out at the `shared.$line-height--base`
      - [ ] Replace `calc()` with just inline math on `.code` and `.na`
      - [ ] Remove vestigial `$levels: 1, 2, 3, 4, 5, 6;`

[See "Guide to the Data" section of the content doc.](https://docs.google.com/document/d/1IXfbbfHew7bq4emEeXNC99-3vR0uA1HWP3dP5g43BLM/edit#heading=h.146g8t2zijgj)

**Comment by reefdog** [comment]
Re: the tips, as noted in #312 (which I just closed to combine with this issue), @ericaryan suggested and @joelwluther concurred with the following ideas:

> A warning that major fields are entered as free text, so users may need to standardize references to Donald Trump, for example; warnings about duplicate entries (depending on how we handle them ourselves); notes on the date fields (depending on how we handle them ourselves). I didn't think it would probably go beyond about a half-dozen.

**Comment by ericaryan** [comment]
We're thinking it might make sense to combine the Format + Schema sections. My initial idea for the "technical details" was really just to have a sentence or two, so it seems like too much focus to have such a big section on the page.

We're thinking we could put both sections under the "What can I expect when I download the data?" question header.

Answer would be:

The Fact-Check Insights dataset is available for download in both JSON and CSV formats.

Not every fact-check will contain data for every field in the dataset, but the main components are:
[schema table]

**Comment by reefdog** [comment]
@ericaryan I think that's good!

**Comment by joelwluther** [comment]
Tips content here: https://docs.google.com/document/d/1bPR7-96sE6Ut6Vp71u0rDXkJnt56KCqLvnlUoAHpL2s/edit

**Comment by reefdog** [comment]
[From @ericaryan](https://github.com/TechAndCheck/zenodotus/issues/266#issuecomment-1313877772):

> We're still figuring out what's going on with a few fields, but the descriptions for the schema table are here: https://docs.google.com/spreadsheets/d/1ZiV8-ks4AL2wqeKKkcuoI84GdMRZUE8xSQ87tCh2-8k/edit?usp=sharing

**Comment by reefdog** [comment]
@ericaryan @joelwluther What do y'all think about adding an "example" column to that schema table? That can be helpful for things like "should this be a URL? a name?" etc.

**Comment by ericaryan** [comment]
Sure. Do we want to chose from the actual data or do you think it would be better to make something up?

**Comment by reefdog** [comment]
I think it's perfectly fine to choose from real data, though I leave it to you whose you want to highlight. 😆

**Comment by reefdog** [comment]
One more thought: what do you think about a column for data type? Realizing that's useful too. Only really relevant in a JSON context (since in a CSV all values are strings) but still, e.g.

- String
- Object
- Integer
- Boolean
- Array of (one of the above)

**Comment by ericaryan** [comment]
Uhhh, I will let @joelwluther take that question

**Comment by joelwluther** [comment]
Hmm, my gut tells me that info would be more useful to people making the data, not necessarily people downloading it for research, etc. I think I'd be happy to leave it off.

**Comment by reefdog** [comment]
The argument for including it is if you're working with the JSON, it can be nice to know what sort of data you're dealing with in a given field. But! That's a purely theoretical pitch + easily determined by just… looking at the example value. Leaving it off does give us more room on the table, so, happy to do so!
