### ISSUE TITLE
Pick team photos

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#392]
The About page ([XD link](https://xd.adobe.com/view/082065b6-ada4-454e-a03c-80defb22f2e7-5d73/screen/5f004dab-5338-4063-b03d-368f421d240e/)) contains photos and bios for the lab team. Everyone should either 👍 their current photo choice, or provide a replacement for Joanna to clip and stylize. (@cguess and @ericaryan in particular have low-res photos).

I'm assigning this task to everyone involved to individually give their approval or provide replacement!

![team](https://user-images.githubusercontent.com/4731/194611957-8d94d54f-9d9e-4440-8cd3-98b5021fcc07.jpeg)

**Comment by BillAdairDuke** [comment]
Mine looks great. Thanks!

**Comment by joelwluther** [comment]
Happy with mine!

**Comment by ericaryan** [comment]
![erica_ryan](https://user-images.githubusercontent.com/18681520/194923554-ac2f6465-1342-4ac8-a9f2-c6c141858fb7.jpg)
Is this better quality?

**Comment by cguess** [comment]
![](https://files.slack.com/files-pri/T6M4MR9S6-F0486EZFGBX/t6m4mr9s6-u7mhmdhmj-ed620943c4e2-512-2.jpeg)

**Comment by cguess** [comment]
![T6M4MR9S6-U7MHMDHMJ-ed620943c4e2-512-2](https://user-images.githubusercontent.com/322626/198152753-21172ea7-426e-4e78-a42b-8bf1afca271c.jpeg)

**Comment by reefdog** [comment]
@joannafonte I leave it up to you to decide if you think we need to clip everyone's backgrounds out or not. May reach a point of diminishing returns on that one, lol.

**Comment by oneroyalace** [comment]
![6F3A5137](https://user-images.githubusercontent.com/9507998/198726137-da4cd484-b944-4794-9c54-6fa02d447ad1.png)

Heeeeeeeeere's Asa!

**Comment by reefdog** [comment]
I found this fantastic photo of @markstencel and nominate it for inclusion.

![stencel2018crop-scaled](https://user-images.githubusercontent.com/4731/199616837-998a127c-4d9c-49b5-811e-436ccf10af28.jpg)

**Comment by reefdog** [comment]
With all of these collected, I'm closing this and kicking the rest of the work over to #429.
