### ISSUE TITLE
Provide opt-out notice instructions

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#422]
Multiple places around the site, we direct folks to an "Opt Out" page for instructions about removing their data from the database. We need these instructions written.

- If the instructions are short (1–2 sentences), then I recommend replacing the link to this page with just putting those instructions inline where we need them (Download page, Guide page, and Contact page).
- If the instructions are longer than 1–2 sentences, we can/should keep them on that specific page.

**Comment by reefdog** [comment]
One recommendation: if the instructions are going to include "email us at [email address]", we can compose the mailto link so that it prefills the email's subject line, and can even prefill the body of the email with some prompts. E.g.:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/4731/199307794-807ffd92-8be1-4095-a89b-ca62a5e3f5ad.png">

**Comment by reefdog** [comment]
Oh, and another thought: is there a concept of "Opt Out" in MediaVault?

**Comment by joelwluther** [comment]
- What we have there now is great ("If you’d like for us to remove your organization’s data from the dataset, please email hello@factcheckinsights.org and let us know.")
- Agree about inline instructions on those pages, but keep the Opt Out page so we can link it from the footer.
- The prefill example is perfect.
- Opt Out for Vault is exactly the same as for Insights.
