### ISSUE TITLE
Create final versions of team photos

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#429]
Using the photos collected in #392, let's generate final versions of the team photos:

- Black and white
- Perfectly square
- No matte (I will add it in CSS)
- 1000px × 1000px

I'm totally indifferent as to whether the backgrounds need to be removed (as in the existing designs) or kept. I leave that up to your design and willingness to tackle the difficult task, lol.

**Comment by joannafonte** [comment]
<img width="500" alt="Erica_team photo" src="https://user-images.githubusercontent.com/60792643/199787891-6a410dbf-9470-4808-a888-06e9a55cbaee.png">
<img width="500" alt="Mark_team photo" src="https://user-images.githubusercontent.com/60792643/199787914-caeaa811-a320-491e-9507-071f400adf5f.png">
<img width="500" alt="Bill_team photo" src="https://user-images.githubusercontent.com/60792643/199787931-ee53e108-44c7-49af-950d-bd7b0b4c542a.png">
<img width="500" alt="Joel_team photo" src="https://user-images.githubusercontent.com/60792643/199787942-05cae052-bd01-4d62-b0d7-869aeb82b9c2.png">
<img width="500" alt="Chris_team photo" src="https://user-images.githubusercontent.com/60792643/199787949-a62d783b-8674-4f69-b851-6219d93bd186.png">
<img width="500" alt="Asa_team photo" src="https://user-images.githubusercontent.com/60792643/199787956-a467817c-bab2-483b-a8ca-292022ea50a1.png">

**Comment by reefdog** [comment]
:pray: Thanks Joanna!
