### ISSUE TITLE
Fact-Check Insights users can't download data

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#433]
Well, this is a sort of big bug!

When non-admin users attempt to download data, they hit the unauthorized wall. This is because they fail [`can_access_fact_check_insights?`](https://github.com/TechAndCheck/zenodotus/blob/a029126c2ad6225a28bfb45b2920a4a5a1db4f9a/app/models/user.rb#L95), and _that's_ because they fail `self.is_fact_check_insights_user?`, which… is not actually a valid method!

**The reason:**

When creating the roles in 9acb2dd78a247715a6f6301af61ec1d82de3ae6a, I chose the shorthand `insights_user` to denote users with access to Fact-Check Insights, while going with `media_vault_user` for MediaVault users. (This is because I thought `fact_check_insights` was too long of a string to regularly use.) So the magic Rolify method for determining if this user is an Insights-permitted user is actually `is_insights_user?`.

**The fix:**

The quick fix would just be to repair `can_access_fact_check_insights?` with the correct check. However! I actually think we should rename the role from `insights_user` to `fact_check_insights_user`. Since the original decision, I've added the idea of ["site definitions"](https://github.com/TechAndCheck/zenodotus/blob/master/config/initializers/site_definitions.rb) and the importance of a site [`shortname`](https://github.com/TechAndCheck/zenodotus/blob/a029126c2ad6225a28bfb45b2920a4a5a1db4f9a/config/initializers/site_definitions.rb#L3), and I think these roles should reflect the shortname explicitly.

So, the task at hand: update the role name from `insights_user` to `fact_check_insights_user`, and ensure downloading data works. Oh and also _add testsstsststssts_.

**Comment by oneroyalace** [comment]
Nice bug find!

**Comment by reefdog** [comment]
Thanks! And thanks also for not calling attention to my repeated roll/role typo. 🤦
