### ISSUE TITLE
Only show "Archive URL" function to admins

### ISSUE THREAD

**Issue by reefdog** [TechAndCheck/zenodotus#441]
On the currently-deployed MediaVault, we show the Archive URL function (which is intended only for development/QA purposes) to all users.

Instead, it should only show to admins.

**Comment by reefdog** [comment]
@cguess In addition to hiding the element from the navbar, I intend to also lock down the relevant controller actions. I'm definitely locking down [`add`](https://github.com/TechAndCheck/zenodotus/blob/c0bc07c6859e9fc437e2db912314593e7b8b96df/app/controllers/media_vault/archive_controller.rb#L18) (which just renders the form), but should I also lock down [`submit_url`](https://github.com/TechAndCheck/zenodotus/blob/c0bc07c6859e9fc437e2db912314593e7b8b96df/app/controllers/media_vault/archive_controller.rb#L25-L66) (which is the `POST` handler for the form)? Or is that intended to be used by the API or Hypatia integration somehow?

**Comment by cguess** [comment]
If it's not used yet, then just go with it.

**Comment by reefdog** [comment]
Sorry, I don't follow. I don't know of anything using it besides as the handler for that ad-hoc Archive URL function, but I don't know if anything else is invisibly using it. I don't want to break something like I did with ingestion that time.

**Comment by cguess** [comment]
Nothing except the route is using it.
