### ISSUE TITLE
Set up scraping infrastructure for Insights

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#496]
Scraping for Insights is going to be quite fundamentally different from the stuff that Zenodotus is doing already for MediaReview. Instead of getting pushed what we want to scrape we have to go out and find it. This requires something bigger, something more nimble and something more ubiquitous that can take any URL and go through the whole site looking for any ClaimReview or MediaReview we can find.

While I'm a fan of monoliths this type of thing is also already handled by other projects. The best known and most used is probably [Scrapy](https://scrapy.org). This is a project in Python that is designed to handle situations exactly like this, and can be deployed to some pretty great infrastructure out of the box. We write what we're looking for the spider to find (in Python, but we can all handle that) and then let it go on our list of URLs. From there we can set it to push anything it finds to Zenodotus for saving/archiving. That way Zenodotus still just receives pushes and if our scraping infrastructure goes down nothing else does.

- [ ] Get list of urls to scrape
- [ ] Set up test Scrapy instance with one URL we know has embedded ClaimReview
- [ ] Test Scrapy to make sure it's picking up what we want
- [ ] Write Zenodotus endpoint to receive ClaimReview/MediaReview (the end point should be agnostic, probably we can modify what we're using for receiving from FactStream)
- [ ] Test full integration
- [ ] Add one more URL, confirm it still works
- [ ] Add five more, etc.
- [ ] Add them all.

**Comment by joelwluther** [comment]
Scraping lists are attached; here are the relevant notes:

The minus_2023_fcmt list is a list of domains that meet the following criteria:

1. They’re in our fact-checking database.
2. The Google API returns ClaimReview data for the domain.
3. They’re not present recently in the FCMT feed (I arbitrarily used 1/1/23 as a cutoff for this)

However, not the best approach? It’s possible for one of them to be in the FCMT this year but to also have earlier ClaimReview data embedded… So the full list of sites that meet 1 and 2 is also attached.

[to_scrape.txt](https://github.com/TechAndCheck/zenodotus/files/11499310/to_scrape.txt)
[to_scrape_minus_2023_fcmt.txt](https://github.com/TechAndCheck/zenodotus/files/11499312/to_scrape_minus_2023_fcmt.txt)

**Comment by cguess** [comment]
Joel Luther (he/him)
  [2:40 PM](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558833916949)
https://zimfact.org/fact-check-yes-remove-nail-polish-or-artificial-nail-from-your-voting-finger/
[2:41](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558865244059)
https://zimfact.org/fact-check-no-this-is-not-a-genuine-call-for-2024-nursing-applications/
[2:41](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558900698909)
https://factcheckni.org/articles/have-social-housing-waiting-lists-almost-doubled-in-20-years/


Chris
  [2:42 PM](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558925686319)
awesome, thank you


Joel Luther (he/him)
  [2:42 PM](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558932809959)
https://factcheckni.org/articles/do-psni-chief-constables-have-the-same-average-tenure-as-other-top-cops-in-the-uk/
[2:42](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558951801699)
Let me know if you need more (either more examples from these sites or examples from other sites)


Chris
  [2:42 PM](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558967619939)
more from others will always be useful
[2:42](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558977263919)
one per site is really all i need


Joel Luther (he/him)
  [2:43 PM](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699558989436039)
okay one sec
[2:45](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699559140874339)
https://namibiafactcheck.org.na/report/no-the-world-food-programme-is-not-recruiting-via-a-whatsapp-post/
[2:46](https://farmers-qlr5927.slack.com/archives/C065ES9Q76V/p1699559177296869)
https://www.dailyo.in/bangla/fact-check/india-today-fact-check-soldier/story/1/33861.html

**Comment by cguess** [comment]
We'll have to write a one-off exception for AfricaCheck
