### ISSUE TITLE
Create CSV version of ClaimReview/MediaReview dataset

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#497]
For the Fact-Check Insights download, we want to make the dataset available as CSV.

Some commentary about implementation here: https://github.com/TechAndCheck/zenodotus/issues/274

**Comment by joelwluther** [comment]
- [ ] [CSV: Handling of firstAppearance](https://github.com/TechAndCheck/zenodotus/issues/568)

- [ ] [CSV: Missing author.sameAs](https://github.com/TechAndCheck/zenodotus/issues/567)
