### ISSUE TITLE
Bring in Simon's Google feed for Insights

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#498]
Google has a number of feeds, there's a specific one that Joel will advise on from Simon at Google which will be a constantly updated feed we need to pull from on a schedule.

The following steps will probably have to happen:

- [x] Get feed info from Simon
- [ ] Create documentation of the feed, since I doubt that Google actually has any and we'll want to reference it
- [x] Write a task that pulls this in, checks for the most recently scraped data and then imports the new stuff
    - [x] Pull data in
    - [x] parse and filter to only media_review (for now)
    - [x] save date 
    - [x] check most recent modified date
    - [x] import
- [x] Automate this job, probably make it a rake task as well
- [x] Decide how often to run. This will depend on how often its updated which will be documented up above.

**Comment by joelwluther** [comment]
https://storage.googleapis.com/datacommons-feeds/factcheck/latest/data.json

**Comment by cguess** [comment]
Skipping the documentation because it's actually extremely self-explanatory
