### ISSUE TITLE
Add instructions for 2FA on multiple devices on settings screen

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#515]
On iPhone XR, iOS 16.4.1 (a)

After entering my username and password, I tap "Click Here to Authenticate With Your Webauthn Key" and it brings up a "Choose how you'd like to sign in to 'factcheckinsights.org'" screen. It has "iPhone, iPad or Android device" selected, which is good. I click "Continue." It brings up a QR code and tells me to scan it, but it's not clear how to do that. If I try to screenshot the QR code, or go to my camera app, the QR code disappears.

**Comment by cguess** [comment]
Did you initially do the set up with the phone as well? I'm attempting to recreate but it's working normally on my device wit the same version of iOS. Is the same Apple account associated with the computer and phone?

**Comment by ericaryan** [comment]
Since this issue turned out to be more about understanding the setup process, I'll suggest some language to add to the "Setting up Two-Factor Authentication" page in Settings.

**Comment by ericaryan** [comment]
This is now covered by #524
