### ISSUE TITLE
Testing: 2FA

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#519]
Test 2FA, including both device/browser passkeys on multiple devices and app authentication. If you find bugs, file them as separate issues.

Initial setup:

- [x] Joel
- [x] Erica
- [x] Asa

Second device:

- [x] Joel
- [x] Erica
- [ ] Asa

App authentication (Authy etc):

- [x] Joel
- [x] Erica
- [x] Asa

Review language for 2FA setup and suggest changes:

- [x] Joel
- [x] Erica

**Comment by ericaryan** [comment]
Reminder: We also need to get someone who doesn't have Apple devices to test this

**Comment by oneroyalace** [comment]
LGTM on android
