### ISSUE TITLE
Temporarily disable FCI download

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#539]
Temporarily disable the download buttons on Fact-Check Insights, just in case someone manages to mosey over there, so they don't get an incomplete dataset

**Comment by cguess** [comment]
Done, replaced with an error box explaining that we're working on it, the actual endpoints for downloading is also disabled so some hacker can't get around it.

**Comment by ericaryan** [comment]
Great! Can we just update the text to say "currently" disabled (typo - just says "current")?

**Comment by ericaryan** [comment]
Looks good!
