### ISSUE TITLE
Expand text search to include CR/MR metadata

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#548]
The text search now only looks at the text of the scraped post. It would be helpful if it could also look at the metadata of the post from ClaimReview/MediaReview.

**Comment by cguess** [comment]
I've expanded it to MediaReview models. Should we search the attached ClaimReview too?

Please test it on the production system

**Comment by ericaryan** [comment]
It seems to be working when I search for specific phrases that I find in the MediaReview. I do think we should add the ClaimReview as well. A lot of times, the claim/statement in a ClaimReview entry attached to a MediaReview entry is a summary of the image/video, which I think would be great for assisting a text search.

**Comment by cguess** [comment]
ClaimReview now in.

**Comment by ericaryan** [comment]
Searching specific phrases that only appear in the ClaimReview are getting proper results.

Does this just search the claim/statement field, or all fields?

**Comment by cguess** [comment]
All the fields that have actual content (so the rating isn't searched for instance)
