### ISSUE TITLE
Occasionally getting blank "media detail" pages

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#558]
https://vault.factcheckinsights.org/media/76937158-f573-4798-bfd7-097c7b9e0110

This one is coming up:
This page isn’t working
vault.factcheckinsights.org is currently unable to handle this request.
HTTP ERROR 500

This has happened before but I haven't documented it because I thought it was just hiccups but now that I've gotten one that's continuing not to work for me, maybe there's a diagnosable issue.

**Comment by cguess** [comment]
I noticed this as well, thanks for bringing it up. Should be fixed.
