### ISSUE TITLE
CSV: Missing author.sameAs

### ISSUE THREAD

**Issue by joelwluther** [TechAndCheck/zenodotus#567]
It's rare, but there are instances where author.sameAs exists in the Google DataFeed but we don't appear to be ingesting it. 

For example, line 96079 in the CSV should match to:

`{
          "@context" : "http://schema.org/",
          "@type" : "ClaimReview",
          "author" : 
          {
            "@type" : "Organization",
            "name" : "WikiTribune",
            "url" : "https://www.wikitribune.com/"
          },
          "claimReviewed" : "Half of older workers have no retirement savings.",
          "datePublished" : "2018-08-01",
          "itemReviewed" : 
          {
            "@type" : "Claim",
            "author" : 
            {
              "@type" : "Person",
              "name" : "Sen. Bernie Sanders",
              "sameAs" : "https://twitter.com/SenSanders/status/1023935529438666752?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwgr%5E383231323b636f6e74726f6c&ref_url=https%3A%2F%2Fwww.wikitribune.com%2Farticle%2F81864%2F"
            },
            "datePublished" : "2018-07-30"
          },
          "reviewRating" : 
          {
            "@type" : "Rating",
            "alternateName" : "Mostly True.",
            "bestRating" : "4",
            "ratingValue" : "3",
            "worstRating" : "1"
          },
          "url" : "https://www.wikitribune.com/wt/news/article/81864/"
        }
      ],
      "url" : "https://www.wikitribune.com/wt/news/article/81864/"
    }`

So, author.sameAs should be `https://twitter.com/SenSanders/status/1023935529438666752?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwgr%5E383231323b636f6e74726f6c&ref_url=https%3A%2F%2Fwww.wikitribune.com%2Farticle%2F81864%2F` but that column appears blank.

**Comment by cguess** [comment]
Is this field in the JSON, or is it missing there as well?

**Comment by joelwluther** [comment]
null in our json

**Comment by cguess** [comment]
Output is now look like
```
   {
      "id": "ebc125b6-e6e6-43db-bc11-d613f0f11752",
      "@context": "https://schema.org",
      "@type": "ClaimReview",
      "author": {
        "@type": "Organization",
        "name": "WikiTribune",
        "url": "https://www.wikitribune.com/",
        "image": null,
        "sameAs": null
      },
      "claimReviewed": "Half of older workers have no retirement savings.",
      "datePublished": "2018-08-01",
      "itemReviewed": {
        "@type": "Claim",
        "datePublished": "2018-07-30",
        "name": null,
        "appearance": null,
        "firstAppearance": null,
        "author": {
          "@type": "Person",
          "name": "Sen. Bernie Sanders",
          "jobTitle": null,
          "image": null,
          "sameAs": "https://twitter.com/SenSanders/status/1023935529438666752?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwgr%5E383231323b636f6e74726f6c&ref_url=https%3A%2F%2Fwww.wikitribune.com%2Farticle%2F81864%2F"
        }
      },
      "reviewRating": {
        "@type": "Rating",
        "ratingValue": "3",
        "bestRating": "4",
        "worstRating": "1",
        "ratingExplanation": null,
        "image": null,
        "alternateName": "Mostly True."
      },
      "url": "https://www.wikitribune.com/wt/news/article/81864/"
    },
```
This should be fixed, please review and close if it passes
