### ISSUE TITLE
CSV: handling of firstApperance

### ISSUE THREAD

**Issue by joelwluther** [TechAndCheck/zenodotus#568]
It looks like we're duplicating fields from `itemReviewed.appearance.1.url ` into `itemReviewed.firstAppearance.url`. That shouldn't always be the case, as there's a separate flag for `firstAppearance`.

**Comment by cguess** [comment]
Ackownledged

**Comment by joelwluther** [comment]
Taking for example the first row of the CSV, ID: `6c4f3a30-2ec1-4e2e-9b57-41ad876223e5`

In the Google DataFeed, this entry looks like:

```
 {
      "@type" : "DataFeedItem",
      "dateCreated" : "2021-04-28T04:51:18.833622+00:00",
      "item" : 
      [
        {
          "@context" : "http://schema.org",
          "@type" : "ClaimReview",
          "author" : 
          {
            "@type" : "Organization",
            "name" : "FACTLY",
            "url" : "https://factly.in/"
          },
          "claimReviewed" : "\u0c39\u0c3e\u0c32\u0c40\u0c35\u0c41\u0c21\u0c4d \u0c28\u0c1f\u0c41\u0c21\u0c41 \u0c2e\u0c46\u0c32\u0c4d \u0c17\u0c3f\u0c2c\u0c4d\u0c38\u0c28\u0c4d \u0c1c\u0c40\u0c35\u0c3f\u0c24\u0c02\u0c32\u0c4b \u0c1a\u0c4b\u0c1f\u0c41\u0c1a\u0c47\u0c38\u0c41\u0c15\u0c41\u0c28\u0c4d\u0c28 \u0c06\u0c1f\u0c41\u0c2a\u0c4b\u0c1f\u0c4d\u0c32\u0c28\u0c3f \u0c35\u0c3f\u0c35\u0c30\u0c3f\u0c02\u0c1a\u0c47 \u0c2e\u0c46\u0c38\u0c47\u0c1c\u0c4d",
          "datePublished" : "2021-04-27",
          "itemReviewed" : 
          {
            "@type" : "Claim",
            "appearance" : 
            [
              {
                "@type" : "CreativeWork",
                "url" : "https://www.facebook.com/groups/471371880599633/permalink/477431856660302"
              }
            ],
            "author" : 
            {
              "@type" : "Person",
              "name" : "SOCIAL MEDIA POST"
            },
            "datePublished" : "2021-04-24"
          },
          "reviewRating" : 
          {
            "@type" : "Rating",
            "alternateName" : "FALSE",
            "bestRating" : "5",
            "image" : "https://factly.in/wp-content/uploads//2018/12/False.png",
            "ratingExplanation" : "\u0c39\u0c3e\u0c32\u0c40\u0c35\u0c41\u0c21\u0c4d \u0c28\u0c1f\u0c41\u0c21\u0c41 \u0c2e\u0c46\u0c32\u0c4d \u0c17\u0c3f\u0c2c\u0c4d\u0c38\u0c28\u0c4d \u0c38\u0c02\u0c2c\u0c02\u0c27\u0c3f\u0c02\u0c1a\u0c3f \u0c37\u0c47\u0c30\u0c4d \u0c05\u0c35\u0c41\u0c24\u0c41\u0c28\u0c4d\u0c28 \u0c08 \u0c2e\u0c46\u0c38\u0c47\u0c1c\u0c4d \u0c1a\u0c3e\u0c32\u0c3e \u0c35\u0c30\u0c15\u0c41 \u0c15\u0c32\u0c4d\u0c2a\u0c3f\u0c24\u0c02. \u0c24\u0c28 \u0c1c\u0c40\u0c35\u0c3f\u0c24\u0c02\u0c32\u0c4b \u0c1c\u0c30\u0c3f\u0c17\u0c3f\u0c28 \u0c15\u0c4a\u0c28\u0c4d\u0c28\u0c3f \u0c38\u0c02\u0c18\u0c1f\u0c28\u0c32\u0c15\u0c3f \u0c15\u0c32\u0c4d\u0c2a\u0c3f\u0c24 \u0c15\u0c25\u0c32\u0c28\u0c3f \u0c1c\u0c4b\u0c21\u0c3f\u0c38\u0c4d\u0c24\u0c42 \u0c08 \u0c2e\u0c46\u0c38\u0c47\u0c1c\u0c4d \u0c28\u0c3f \u0c37\u0c47\u0c30\u0c4d \u0c1a\u0c47\u0c38\u0c4d\u0c24\u0c41\u0c28\u0c4d\u0c28\u0c3e\u0c30\u0c41",
            "ratingValue" : "1",
            "worstRating" : "1"
          },
          "sdPublisher" : 
          {
            "@type" : "Organization",
            "name" : "Google Fact Check Tools",
            "url" : "https://g.co/factchecktools"
          },
          "url" : "https://factly.in/telugu-most-parts-of-this-message-that-describes-the-events-in-hollywood-actor-mel-gibson-is-fictional/"
        }
      ],
      "url" : "https://factly.in/telugu-most-parts-of-this-message-that-describes-the-events-in-hollywood-actor-mel-gibson-is-fictional/"
    }

```

So, there's not a firstAppearance there -- but in our downloads, we're parsing appearance.1(.children) as the firstAppearance.

**Comment by joelwluther** [comment]
There's a dual problem, where we might be submitting to the Google API through the FactStream interface things as firstAppearance where they shouldn't be; as we don't have that capability in FactStream. 

Ex:

```
{
      "@type" : "DataFeedItem",
      "dateCreated" : "2021-04-28T01:47:01.48205+00:00",
      "item" : 
      [
        {
          "@context" : "http://schema.org",
          "@type" : "ClaimReview",
          "author" : 
          {
            "@type" : "Organization",
            "image" : "https://d10r9aj6omusou.cloudfront.net/factstream-logo-image-61554e34-b525-4723-b7ae-d1860eaa2296.png",
            "name" : "PolitiFact",
            "url" : "https://www.politifact.com/"
          },
          "claimReviewed" : "\u201cHuman trafficking and drugs\u201d at the Mexico border have \u201cdoubled, tripled and quadrupled\u201d since Joe Biden became president.",
          "itemReviewed" : 
          {
            "@type" : "Claim",
            "appearance" : 
            [
              {
                "@type" : "CreativeWork",
                "url" : "https://www.facebook.com/DonaldJTrumpJr/videos/vb.295644160460352/453225989241426/?type=2&theater"
              }
            ],
            "author" : 
            {
              "@type" : "Person",
              "image" : "https://www.factstream.co/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnJJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4729ba8790d66da25c72a09d3ffe2340f059d4be/3a3e6c7b-7b6c-46a4-812e-144119fac679.jpg?disposition=attachment",
              "jobTitle" : "Former president",
              "name" : "Donald Trump"
            },
            "datePublished" : "2021-04-20",
            "firstAppearance" : 
            {
              "@type" : "CreativeWork",
              "url" : "https://www.facebook.com/DonaldJTrumpJr/videos/vb.295644160460352/453225989241426/?type=2&theater"
            },
            "name" : "Interview"
          },
          "reviewRating" : 
          {
            "@type" : "Rating",
            "alternateName" : "False",
            "bestRating" : "9",
            "image" : "https://www.factstream.co/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBZ3ciLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--515ab59b0dc06bbc4032da94253cbef2b8c260a4/https-3A-2F-2Fdhpikd1t89arn.cloudfront.net-2Frating_images-2Fpolitifact-2Ftom-false.jpg?disposition=attachment",
            "ratingExplanation" : "Experts say it takes time after someone enters the U.S. for them to be subjected to sex or labor trafficking, and there aren\u2019t statistics yet for Biden\u2019s presidency. The number of drug seizure events is up 11%.",
            "ratingValue" : "4",
            "worstRating" : "0"
          },
          "sdPublisher" : 
          {
            "@type" : "Organization",
            "name" : "Google Fact Check Tools API",
            "url" : "https://g.co/factchecktools"
          },
          "url" : "https://www.politifact.com/factchecks/2021/apr/27/donald-trump/no-proof-trumps-claim-surge-trafficking-drugs-bord/"
        }
      ],
      "url" : "https://www.politifact.com/factchecks/2021/apr/27/donald-trump/no-proof-trumps-claim-surge-trafficking-drugs-bord/"
    }
```

**Comment by cguess** [comment]
Two points:

1. On FactStream we do do this when submitting https://github.com/TechAndCheck/factstream-backend/blob/197eb5451e69a1b205806e1bbfed1f4618f26cab/app/models/fact_check.rb#L784C1-L785C1 Should this not be the case?
2. Here, should we compare the two and remove the first if it's duplicated?

**Comment by cguess** [comment]
@ericaryan and I have come up with the following options. @joelwluther please check it out
1. We fix the auto-filling of `firstAppearance` in FactStream as linked to above
2. I write a script that
    1. Retrieves all claims from Insights for our FactStream partners
    2. Goes through every entry and check if `firstAppearance` and `appearances[0]` is the same
    3. If it is, set `firstAppearance` to nil
    4. Save it if necessary

**Comment by cguess** [comment]
I will out put a list of any that don't meet this condition

**Comment by joelwluther** [comment]
Gotcha! Still need to talk about the non-FactStream users, maybe after our meeting with Chengkai? See the Factly example above.

**Comment by joelwluther** [comment]
So, for the Factly example, compare the above from the Google DataFeed to our JSON:

```
{
      "id": "8e7bce6b-a9f0-4b5a-99de-e6479f6fcb39",
      "@context": "https://schema.org",
      "@type": "ClaimReview",
      "author": {
        "@type": "Organization",
        "name": "FACTLY",
        "url": "https://factly.in/",
        "image": null,
        "sameAs": null
      },
      "claimReviewed": "హాలీవుడ్ నటుడు మెల్ గిబ్సన్ జీవితంలో చోటుచేసుకున్న ఆటుపోట్లని వివరించే మెసేజ్",
      "datePublished": "2021-04-27",
      "itemReviewed": {
        "@type": "Claim",
        "datePublished": "2021-04-24",
        "name": null,
        "appearance": [
          {
            "url": "https://www.facebook.com/groups/471371880599633/permalink/477431856660302",
            "@type": "CreativeWork"
          }
        ],
        "firstAppearance": {
          "url": "https://www.facebook.com/groups/471371880599633/permalink/477431856660302",
          "@type": "CreativeWork"
        },
        "author": {
          "@type": "Person",
          "name": "SOCIAL MEDIA POST",
          "jobTitle": null,
          "image": null,
          "sameAs": null
        }
      }
```

**Comment by ericaryan** [comment]
> @ericaryan and I have come up with the following options. @joelwluther please check it out
> 
> 1. We fix the auto-filling of `firstAppearance` in FactStream as linked to above
> 2. I write a script that
>    
>    1. Retrieves all claims from Insights for our FactStream partners
>    2. Goes through every entry and check if `firstAppearance` and `appearances[0]` is the same
>    3. If it is, set `firstAppearance` to nil
>    4. Save it if necessary

Just noting that we want to add a step after step 1 where we fix the download so that it doesn't show a firstAppearance, except when it exists in the Google feed. (Right now, every entry gets one, even if it's not supposed to.)

**Comment by cguess** [comment]
@joelwluther should test this now

**Comment by joelwluther** [comment]
Looks great, dupes removed as expected.

There's another case where, for whatever reason, there's data in `firstAppearance` where there's no data in `appearance.1`.

Given that FactStream doesn't have `firstAppearance` capability, we also want to move those over to `appearance.1`.

So, copy data from `firstAppearance` to `appearance.1`, then set `firstAppearance` to null.

Here's an example:

` {
      "@type" : "DataFeedItem",
      "dateCreated" : "2021-02-09T13:23:30.772522+00:00",
      "item" : 
      [
        {
          "@context" : "http://schema.org",
          "@type" : "ClaimReview",
          "author" : 
          {
            "@type" : "Organization",
            "image" : "https://d10r9aj6omusou.cloudfront.net/factstream-logo-image-009b0bde-cf0d-48c3-86ab-7c8a1510a320.jpeg",
            "name" : "Washington Post",
            "url" : "https://www.washingtonpost.com/"
          },
          "claimReviewed" : "\u201cI do think that we should have a minimum wage, stand by itself, $15 an hour and work your way up to the \u2014 it doesn\u2019t have to be boom. And all the economics show, if you do that, the whole economy rises.\u201d",
          "itemReviewed" : 
          {
            "@type" : "Claim",
            "author" : 
            {
              "@type" : "Person",
              "image" : "https://www.factstream.co/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajNEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9e68c9404cee2f9c7c49048b26dfd242afc2e841/cb080acc-09ce-4c29-ba97-c818b998054c.jpg?disposition=attachment",
              "jobTitle" : "President",
              "name" : "Joe Biden"
            },
            "datePublished" : "2021-02-05",
            "firstAppearance" : 
            {
              "@type" : "CreativeWork",
              "url" : "https://www.cnn.com/videos/media/2021/02/05/biden-covid-relief-bill-minimum-wage-hike-cbs-interview-vpx.cnn/video/playlists/this-week-in-politics/"
            },
            "name" : " in an interview with Norah O\u2019Donnell of CBS News"
          },
          "reviewRating" : 
          {
            "@type" : "Rating",
            "alternateName" : "Two Pinocchios",
            "bestRating" : "5",
            "image" : "https://www.factstream.co/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBZ3ciLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--515ab59b0dc06bbc4032da94253cbef2b8c260a4/https-3A-2F-2Fdhpikd1t89arn.cloudfront.net-2Frating_images-2Fwashpo-2Fwashpo_pinnochios_2.png?disposition=attachment",
            "ratingExplanation" : "Biden is bullish on a big increase in the minimum wage, but economists are sharply divided on the impact on jobs.",
            "ratingValue" : "2",
            "worstRating" : "0"
          },
          "sdPublisher" : 
          {
            "@type" : "Organization",
            "name" : "Google Fact Check Tools API",
            "url" : "https://g.co/factchecktools"
          },
          "url" : "https://www.washingtonpost.com/politics/2021/02/09/bidens-claim-that-with-15-minimum-wage-whole-economy-rises/"
        }
      ],
      "url" : "https://www.washingtonpost.com/politics/2021/02/09/bidens-claim-that-with-15-minimum-wage-whole-economy-rises/"
    }`

**Comment by joelwluther** [comment]
lgtm
