### ISSUE TITLE
Data download/MediaReview: remove extraneous data

### ISSUE THREAD

**Issue by joelwluther** [TechAndCheck/zenodotus#570]
The columns/fields highlighted in yellow in the [schema table](https://docs.google.com/spreadsheets/u/1/d/1ZiV8-ks4AL2wqeKKkcuoI84GdMRZUE8xSQ87tCh2-8k/edit#gid=693581661) are extraneous and we'd like to remove them from the JSON/CSV download.

**Comment by ericaryan** [comment]
I was double-checking this info and made a list of the fields for my own benefit, so I'm including it here for handy reference:

author.image
author.sameAs
itemReviewed.creator.@type
itemReviewed.creator.name
itemReviewed.creator.url
itemReviewed.interpretedAsClaim.@type
itemReviewed.interpretedAsClaim.description
itemReviewed.mediaItemAppearance.1.accessedOnUrl
itemReviewed.mediaItemAppearance

**Comment by cguess** [comment]
> itemReviewed.mediaItemAppearance
So since this is populated in some of the items, but not others I'm going to make this an empty array if there's nothing.

**Comment by cguess** [comment]
This is read to review

**Comment by joelwluther** [comment]
Looks good, I think my only question is tied to my comment on on #571 and whether or not we want to adjust our FactStream output to match the Google DataFeed output. Will need @ericaryan input on that.

**Comment by joelwluther** [comment]
done
