### ISSUE TITLE
Ad hoc archiving

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#610]

**Comment by cguess** [comment]
Some overview of steps needed (I'll break these into sub-issues as I go)

- [ ] Set up staging server
    - [ ] Figure out S3 bucket copying
- [ ] Set up auto-deploy of testing server
- [ ] Get tests to pass completely
- [ ] Add Page for MyVault
- [ ] Add tabs for MyVault
- [ ] Figure out better messaging system from Hypatia to Zenodotus for status updates.
- [ ] Add querying of status to Hypatia
- [ ] Consider other IP addresses for scraping. GreenDesk?
- [ ] Get internet fallover working for more IPs and redundancy
- [ ] Account rotation and management?
- [ ] Add privacy access to MyVault items
- [ ] Search MyVault by text (image?)
- [ ] Do we have a retainment policy? 5 years? 5 months? Request?

**Comment by cguess** [comment]
@ericaryan please verify and close (Most of these checks are separate issues)

**Comment by ericaryan** [comment]
👍
