### ISSUE TITLE
Filter bugs

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#620]
- [ ] Searching works by limiting the results by the date POSTED, but the results are ordered by date ARCHIVED. This matches the default sort of the dashboard, but it can lead to confusing search results, because if you're limiting by a date range, you would expect the oldest and newest posts to be closest to what you filtered by, instead of it being jumbled.
- [ ] If you use today's date as a filter, the field resets to mm/dd/yyyy after you hit the filter button (though this does not seem to affect the results)

**Comment by cguess** [comment]
in regards to point 1: This will require a bit a of reworking. I'll reiterate my comment in the code ```
    # This is bad, but it's working for test purposes
    # The way to *actually* fix this is to add the `posted_at` field to the ArchiveItem as well on save, so it can be filterd properly later
    # In fact, if this comment is still here it means this hasn't been done. So take the hour and DO IT NOW. (says Chris at 7pm)
```

**Comment by ericaryan** [comment]
Ha!! I don't think this needs to be a priority right now. We can come back to it after some of the higher-level things.
