### ISSUE TITLE
URL search bugs

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#625]
- [x] Searching by text now gives an error that it's not a URL.
- [x] After searching by URL, the search box on the results page defaults to searching by uploading media (the "Choose file" status). Do we want it to do that?
- [x] When users want to switch between search methods, we could change the helper text search link underneath the search box from: "You can also search by text" to "You can also search by text or media URL"

**Comment by cguess** [comment]
Turns out point 1 only shows up if there's no space in the search string.
