### ISSUE TITLE
Alternate Instagram link format breaks scrapers

### ISSUE THREAD

**Issue by joelwluther** [TechAndCheck/zenodotus#641]
Links of this format do not work when attempting to save to MyVault: https://www.instagram.com/9thstreetjournal/p/C4qqX1LvBbU/

But links of this format do: https://www.instagram.com/p/C4qqX1LvBbU/

Unclear if this also happens when we're also doing the standard MediaReview ingest, but worth investigating.

**Comment by cguess** [comment]
Confirm and close @ericaryan
