### ISSUE TITLE
Duplication in searching MyVault

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#642]
When searching MyVault for privately saved posts, the same posts are showing twice in search results

<img width="1398" alt="Screenshot 2024-03-20 at 1 44 36 PM" src="https://github.com/TechAndCheck/zenodotus/assets/18681520/9d616a37-06e3-4758-83d0-108b63241e7d">

<img width="1325" alt="Screenshot 2024-03-20 at 1 30 28 PM" src="https://github.com/TechAndCheck/zenodotus/assets/18681520/ee023146-6090-4521-8f95-14325b7c41e3">

**Comment by cguess** [comment]
This should be fixed unless the same post is archived twice @ericaryan

**Comment by ericaryan** [comment]
<img width="1174" alt="Screenshot 2024-03-29 at 10 52 51 AM" src="https://github.com/TechAndCheck/zenodotus/assets/18681520/8a22b90f-48fb-4550-8bb3-e78a85ae48d3">
Getting lots of dupes when searching

**Comment by ericaryan** [comment]
Duplication is fixed!
