### ISSUE TITLE
Add ID number to emails (or remove the request)

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#648]
The email you get when the scraper has an error or the post is gone tells you to submit an ID number but doesn't include the ID number:
"Please include the URL and the ID # in your email and we will look into the problem as soon as possible."

We either need to add the number or remove that part and just tell them to include the URL.

**Comment by cguess** [comment]
@ericaryan check please.

**Comment by ericaryan** [comment]
Confirmed!
