### ISSUE TITLE
MediaVault: Integration of Fact Check Explorer API search

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#689]
Expand search feature to include results from Fact Check Explorer's reverse image search API

**Comment by joelwluther** [comment]
![mockup-detail-page](https://github.com/user-attachments/assets/8982bd17-00ec-41d0-ad70-b76d1bcd48ef)

**Comment by ericaryan** [comment]
![signal-2024-09-23-142459_002](https://github.com/user-attachments/assets/474ca7d9-7fd0-404d-852c-47af6f9afcd0)

**Comment by joelwluther** [comment]
Couple of bugs that jumped out to me:

- [ ]  Count at the top is off, for "XX matching FCE results found"

![image](https://github.com/user-attachments/assets/97009ea0-d2b6-4b05-8dbe-43d44c01ceef)

- [ ] Image previews appear squished in the FCE results:

![image](https://github.com/user-attachments/assets/f3dd668b-1d34-48a5-a1d9-d61d16ca56d6)

**Comment by ericaryan** [comment]
Getting "this page isn't working" when searching some images. Examples:
![facebook_media_ead530fe-f6d1-4b1c-aabb-6e667a637b80](https://github.com/user-attachments/assets/bc56066d-c713-41b8-90a9-3b9928afe676)
![lively](https://github.com/user-attachments/assets/4d72f578-9bff-4646-a54c-33ed0bc5a32f)
