### ISSUE TITLE
MediaVault: Implement public-facing links for archived posts

### ISSUE THREAD

**Issue by ericaryan** [TechAndCheck/zenodotus#690]
Allow fact-checkers to link to the posts they've archived in a publicly accessible way

**Comment by joelwluther** [comment]
Homepage: 
![image](https://github.com/user-attachments/assets/b319488d-d763-461e-9fd4-9b435685cb5c)

**Comment by joelwluther** [comment]
Detail page: 
![mockup-detail-page](https://github.com/user-attachments/assets/9f86141c-1e3a-49d4-844e-a94244f223ce)
