### ISSUE TITLE
Add organizational logins

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/zenodotus#74]
We'll want to add organization associations at some point. What that'll look like is anyone's guess, but I'm putting this here for record keeping.

**Comment by reefdog** [comment]
Putting this issue in the icebox (after consultation w/@cguess of course) because until we better understand the organizational use case, we don't want to bother.

**Comment by reefdog** [comment]
We've decided not to pursue orgs at all; closing this and will be removing organization code in #302.
