### ISSUE TITLE
Add MFA to the site

### ISSUE THREAD

**Issue by cguess** [TechAndCheck/zenodotus#8]
Depends on #7

**Comment by reefdog** [comment]
Googled around a bit, surfacing a few projects to look at:

- https://github.com/wmlele/devise-otp: Small project but actively-maintained and with current Rails compatibility.
- https://github.com/Houdini/two_factor_authentication: Stale project (see [this issue](https://github.com/Houdini/two_factor_authentication/issues/193)), but seemed to have been quite popular, so may be a good starting point for "alternatives to…" searches.
- https://github.com/baarkerlounger/two_factor_authentication: Lightly modernized version of the above gem that actually works.

**Comment by cguess** [comment]
In a discussion with @reefdog we've decided to go full webauthn. Luckily there's a write up here https://www.honeybadger.io/blog/multi-factor-2fa-authentication-rails-webauthn-devise/ to do so
